### PR TITLE
Yc newfeature

### PR DESCRIPTION
**Pull request by yasmeencole**
# Description

This feature allows us to view the details for each park, eatery and bizarre selected in the dropdown. 

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)
- [ x ]  This change requires a documentation update pull new main after merge

# Testing Instructions
```
git fetch —all
git checkout yc-newfeature
serve

```

# Checklist:

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings or errors
- [ x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by nathanRomad — DISMISSED** [review]

**Comment by nathanRomad** [comment]
everything looks good.. just make sure to clean up the main.js to remove any conflicts/duplicates..

**Review by nathanRomad — DISMISSED** [review]
can't wait to see all our code come together..
hopefully we can see all the functionality after our latest merge..

**Review by nathanRomad — APPROVED** [review]
we worked on this together and yasmeen walked me through her code!  We should have everything lined up to work..
here comes the testing!

**Review by calebsjames — APPROVED** [review]
Coming together!!!

**Pull request merged**
