### PR TITLE
Nah bizarre dropdown

### PR DESCRIPTION
**Pull request by nathanRomad**
# Description
I created 3 modules.
1. AttractionProvider.js = fetches data from API. created getAttractions and useAttractions.
2. AttractionSelect.js = creates dropdown feature and places it on the DOM.
3. Attraction.js = not used yet... will be used when "details" is clicked on the itineraryPreview

Fixes # (issue) = fully functional dropdown for bizarreries!

- [X] New feature (non-breaking change which adds functionality)
-  [X] This change requires a documentation update
    I changed the <select> tag in the index.html to a div and provided the <select> tag in my rendertoDOM().  Please note the conflict in index.html

----------------------------------
# Testing Instructions
git fetch --all
git checkout nah-bizarreDropdown
serve
----------------------------------
Please check to see the dropdown displays all the bizarres and can be "selected"

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by calebsjames — DISMISSED** [review]
Everything is showing up and looking good!

**Review by kylieanyce — DISMISSED** [review]

**Review by yasmeencole — APPROVED** [review]
looks good

**Review by kylieanyce — APPROVED** [review]
looks good!

**Review by calebsjames — APPROVED** [review]
Looks good.

**Pull request merged**
