### PR TITLE
Nah itinerary preview

### PR DESCRIPTION
**Pull request by nathanRomad**
The ParkPreview is working. When you select a park, it renders the selected park to the DOM and provides a detail button.
The detail button dispatches a customEvent called "parkDetailsClicked".

This module has no dependecy and should not break anything.
This module does have eventListeners attached to it...

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update
pull new main after merge

# Testing Instructions
git fetch --all
git checkout nah-itineraryPreview
git serve

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas - there are not a ton of comments, let me know if you have any questions.
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kylieanyce — DISMISSED** [review]
Great job!!

**Review by calebsjames — DISMISSED** [review]
Looks good and is working!

**Comment by nathanRomad** [comment]
just updated one last time and pushed new changes...
please review, test, and approve as you can..

**Review by calebsjames — DISMISSED** [review]

**Review by yasmeencole — DISMISSED** [review]
This looks amazing!

**Review by calebsjames — APPROVED** [review]
Coming together!

**Review by yasmeencole — APPROVED** [review]
Looks great!

**Review by kylieanyce — APPROVED** [review]

**Pull request merged**
